package flash.reader.types {
    public final class BlockType {
        public static const END:uint                                = 0;
        public static const SHOW_FRAME:uint                         = 1;
        public static const DEFINE_SHAPE:uint                       = 2;
        public static const FREE_CHARACTER:uint                     = 4;
        public static const REMOVE_OBJECT:uint                      = 3; // ?!
        public static const PLACE_OBJECT:uint                       = 5;
        public static const DEFINE_BITS:uint                        = 6;
        public static const DEFINE_BUTTON:uint                      = 7;
        public static const JPEG_TABLES:uint                        = 8;
        public static const SET_BACKGROUND_COLOR:uint               = 9;
        public static const DEFINE_FONT:uint                        = 10;
        public static const DEFINE_TEXT:uint                        = 11;
        public static const DO_ACTION:uint                          = 12;
        public static const DEFINE_FONT_INFO:uint                   = 13;
        public static const DEFINE_SOUND:uint                       = 14;
        public static const START_SOUND:uint                        = 15;
        public static const STOP_SOUND:uint                         = 16; // ?!
        public static const DEFINE_BUTTON_SOUND:uint                = 17;
        public static const SOUND_STREAM_HEAD:uint                  = 18;
        public static const SOUND_STREAM_BLOCK:uint                 = 19;
        public static const DEFINE_BITS_LOSS_LESS:uint              = 20;
        public static const DEFINE_BITS_JPEG_2:uint                 = 21;
        public static const DEFINE_SHAPE_2:uint                     = 22;
        public static const DEFINE_BUTTON_CX_FORM:uint              = 23;
        public static const PROTECT:uint                            = 24;
        public static const PATHS_ARE_POSTSCRIPT:uint               = 25; // ?!
        public static const PLACE_OBJECT_2:uint                     = 26;
        public static const REMOVE_OBJECT_2:uint                    = 28;
        public static const SYNC_FRAME:uint                         = 29; // ?!
        public static const FREE_ALL:uint                           = 31; // ?!
        public static const DEFINE_SHAPE_3:uint                     = 32;
        public static const DEFINE_TEXT_2:uint                      = 33;
        public static const DEFINE_BUTTON_2:uint                    = 34;
        public static const DEFINE_BITS_JPEG_3:uint                 = 35;
        public static const DEFINE_BITS_LOSS_LESS_2:uint            = 36;
        public static const DEFINE_EDIT_TEXT:uint                   = 37;
        public static const DEFINE_VIDEO:uint                       = 38; // ?!
        public static const DEFINE_SPRITE:uint                      = 39;
        public static const NAME_CHARACTER:uint                     = 40; // ?!
        public static const PRODUCT_INFO:uint                       = 41; // ?!
        public static const DEFINE_TEXT_FORMAT:uint                 = 42; // ?!
        public static const FRAME_LABEL:uint                        = 43;
        public static const SOUND_STREAM_HEAD_2:uint                = 45;
        public static const DEFINE_MORPH_SHAPE:uint                 = 46;
        public static const GENERATE_FRAME:uint                     = 47; // ?!
        public static const DEFINE_FONT_2:uint                      = 48;
        public static const GENERATOR_COMMAND:uint                  = 49; // ?!
        public static const DEFINE_COMMAND_OBJECT:uint              = 50; // ?!
        public static const CHARACTER_SET:uint                      = 51; // ?!
        public static const EXTERNAL_FONT:uint                      = 52; // ?!
        public static const EXPORT_ASSETS:uint                      = 56;
        public static const IMPORT_ASSETS:uint                      = 57;
        public static const ENABLE_DEBUGGER:uint                    = 58;
        public static const DO_INIT_ACTION:uint                     = 59;
        public static const DEFINE_VIDEO_STREAM:uint                = 60;
        public static const VIDEO_FRAME:uint                        = 61;
        public static const DEFINE_FONT_INFO_2:uint                 = 62;
        public static const DEBUG_ID:uint                           = 63; // ?!
        public static const ENABLE_DEBUGGER_2:uint                  = 64;
        public static const SCRIPT_LIMITS:uint                      = 65;
        public static const SET_TAB_INDEX:uint                      = 66;
        public static const FILE_ATTRIBUTES:uint                    = 69;
        public static const PLACE_OBJECT_3:uint                     = 70;
        public static const IMPORT_ASSETS_2:uint                    = 71;
        public static const DO_ABC_DEFINE:uint                      = 72; // ?!
        public static const DEFINE_FONT_ALIGN_ZONES:uint            = 73;
        public static const CSM_TEXT_SETTINGS:uint                  = 74;
        public static const DEFINE_FONT_3:uint                      = 75;
        public static const SYMBOL_CLASS:uint                       = 76;
        public static const METADATA:uint                           = 77;
        public static const DEFINE_SCALING_GRID:uint                = 78;
        public static const DO_ABC:uint                             = 82;
        public static const DEFINE_SHAPE_4:uint                     = 83;
        public static const DEFINE_MORPH_SHAPE_2:uint               = 84;
        public static const DEFINE_SCENE_AND_FRAME_LABEL_DATA:uint  = 86;
        public static const DEFINE_BINARY_DATA:uint                 = 87;
        public static const DEFINE_FONT_NAME:uint                   = 88;
        public static const START_SOUND_2:uint                      = 89;
        public static const DEFINE_BITS_JPEG_4:uint                 = 90;
        public static const DEFINE_FONT_4:uint                      = 91;
        public static const ENABLE_TELEMETRY:uint                   = 93;

        public static const LIST:Object                             = { };
    }
}
